### ISSUE TITLE
Change logos for Massa-Wallet

### ISSUE THREAD

**Issue by Kryptopaid** [massalabs/massa-wallet#13]
=> Update logo in masssa-wallet-main > popup with: 
![massa](https://user-images.githubusercontent.com/81397547/165075190-2e5945ca-fcf7-47fb-a4e7-d0d1272b73f3.png)
)
=> Update Browser Extension logo in massa-wallet-main > icons with
![massa-logo](https://user-images.githubusercontent.com/81397547/165075371-83527a62-cd6f-4755-97ad-bc6c07d60237.png)

**Comment by qdrn** [comment]
See #4...

Closing
